Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Bad Request: /
"GET / HTTP/1.1" 400 74579
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
"GET /favicon.ico HTTP/1.1" 400 74515
Bad Request: /xero/login/
"GET /xero/login/ HTTP/1.1" 400 0
Internal Server Error: /xero/login/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Users\scorp\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\scorp\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\scorp\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Users\scorp\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type RuntimeError is not JSON serializable
"GET /xero/login/ HTTP/1.1" 500 104119
Internal Server Error: /xero/login/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 104, in get
    response = login(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 51, in login
    return oauth.xero.authorize_redirect(request, redirect_uri)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\authlib\integrations\django_client\apps.py", line 25, in authorize_redirect
    rv = self.create_authorization_url(redirect_uri, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\authlib\integrations\base_client\sync_app.py", line 313, in create_authorization_url
    raise RuntimeError('Missing "authorize_url" value')
RuntimeError: Missing "authorize_url" value
"GET /xero/login/ HTTP/1.1" 500 108108
Internal Server Error: /xero/login/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 104, in get
    response = login(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 51, in login
    return oauth.xero.authorize_redirect(request, redirect_uri)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\authlib\integrations\django_client\apps.py", line 25, in authorize_redirect
    rv = self.create_authorization_url(redirect_uri, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\authlib\integrations\base_client\sync_app.py", line 313, in create_authorization_url
    raise RuntimeError('Missing "authorize_url" value')
RuntimeError: Missing "authorize_url" value
"GET /xero/login/ HTTP/1.1" 500 108108
Not Found: /favicon.ico
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
Method Not Allowed: /auth/login/
"GET /auth/login/ HTTP/1.1" 405 40
Forbidden: /xero/login/
"POST /xero/login/ HTTP/1.1" 403 45
Forbidden: /auth/login/
"POST /auth/login/ HTTP/1.1" 403 45
Internal Server Error: /xero/login/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 104, in post
    response = login(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 51, in login
    return oauth.xero.authorize_redirect(request, redirect_uri)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\authlib\integrations\django_client\apps.py", line 25, in authorize_redirect
    rv = self.create_authorization_url(redirect_uri, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\authlib\integrations\base_client\sync_app.py", line 313, in create_authorization_url
    raise RuntimeError('Missing "authorize_url" value')
RuntimeError: Missing "authorize_url" value
"POST /xero/login/ HTTP/1.1" 500 109985
Not Found: /
"GET / HTTP/1.1" 404 2392
Not Found: /xero
"GET /xero HTTP/1.1" 404 2422
Not Found: /xero/
"GET /xero/ HTTP/1.1" 404 2631
Internal Server Error: /xero/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 102, in get
    return render(request, self.template_name)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: code.html
"GET /xero/ HTTP/1.1" 500 97001
Internal Server Error: /xero/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 102, in get
    return render(request, self.template_name)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: code.html
"GET /xero/ HTTP/1.1" 500 96844
Internal Server Error: /xero/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 102, in get
    return render(request, self.template_name)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: code.html
"GET /xero/ HTTP/1.1" 500 96844
Internal Server Error: /xero/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 102, in get
    return render(request, self.template_name)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: code.html
"GET /xero/ HTTP/1.1" 500 96844
Internal Server Error: /xero/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 102, in get
    return render(request, self.template_name)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: code.html
"GET /xero/ HTTP/1.1" 500 96844
Internal Server Error: /xero/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 102, in get
    return render(request, self.template_name)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: code.html
"GET /xero/ HTTP/1.1" 500 96844
Internal Server Error: /xero/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 102, in get
    return render(request, self.template_name)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /xero/ HTTP/1.1" 500 96844
Internal Server Error: /xero/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 102, in get
    return render(request, self.template_name)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: xero/code.html
"GET /xero/ HTTP/1.1" 500 96949
Internal Server Error: /xero/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 102, in get
    return render(request, self.template_name)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: xero/templates/code.html
"GET /xero/ HTTP/1.1" 500 97159
Internal Server Error: /xero/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 102, in get
    return render(request, self.template_name)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: code.html
"GET /xero/ HTTP/1.1" 500 97012
Internal Server Error: /xero/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 102, in get
    return render(request, self.template_name)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: code.html
"GET /xero/ HTTP/1.1" 500 97012
Internal Server Error: /xero/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 102, in get
    return render(request, self.template_name)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: code.html
"GET /xero/ HTTP/1.1" 500 97012
Internal Server Error: /xero/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 102, in get
    return render(request, self.template_name)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: code.html
"GET /xero/ HTTP/1.1" 500 97012
Internal Server Error: /xero/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 102, in get
    return render(request, self.template_name)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: code.html
"GET /xero/ HTTP/1.1" 500 97012
Internal Server Error: /xero/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 102, in get
    return render(request, self.template_name)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'index' not found. 'index' is not a valid view function or pattern name.
"GET /xero/ HTTP/1.1" 500 154756
Internal Server Error: /xero/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 102, in get
    return render(request, self.template_name)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '' not found. '' is not a valid view function or pattern name.
"GET /xero/ HTTP/1.1" 500 154641
Internal Server Error: /xero/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 102, in get
    return render(request, self.template_name)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '/' not found. '/' is not a valid view function or pattern name.
"GET /xero/ HTTP/1.1" 500 154636
Internal Server Error: /xero/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 102, in get
    return render(request, self.template_name)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
"GET /xero/ HTTP/1.1" 500 154619
Internal Server Error: /xero/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 102, in get
    return render(request, self.template_name)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'index' not found. 'index' is not a valid view function or pattern name.
"GET /xero/ HTTP/1.1" 500 154756
Internal Server Error: /xero/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 102, in get
    return render(request, self.template_name)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
"GET /xero/ HTTP/1.1" 500 154619
Internal Server Error: /xero/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 102, in get
    return render(request, self.template_name)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
"GET /xero/ HTTP/1.1" 500 154619
Internal Server Error: /xero/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 102, in get
    return render(request, self.template_name)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
"GET /xero/ HTTP/1.1" 500 154619
Method Not Allowed: /xero/login/
"GET /xero/login/ HTTP/1.1" 405 40
Internal Server Error: /xero/login/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 112, in get
    redirect_url = reverse("oauth_callback")
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'oauth_callback' not found. 'oauth_callback' is not a valid view function or pattern name.
"GET /xero/login/ HTTP/1.1" 500 109015
Internal Server Error: /xero/login/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 112, in get
    redirect_url = reverse("oauth_callback")
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'oauth_callback' not found. 'oauth_callback' is not a valid view function or pattern name.
"GET /xero/login/ HTTP/1.1" 500 109276
Internal Server Error: /xero/login/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 112, in get
    redirect_url = reverse("oauth_callback")
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'oauth_callback' not found. 'oauth_callback' is not a valid view function or pattern name.
"GET /xero/login/ HTTP/1.1" 500 109247
Internal Server Error: /xero/login/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 112, in get
    redirect_url = reverse("oauth_callback")
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'oauth_callback' not found. 'oauth_callback' is not a valid view function or pattern name.
"GET /xero/login/ HTTP/1.1" 500 109247
Internal Server Error: /xero/login/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 112, in get
    redirect_url = reverse("oauth_callback")
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'oauth_callback' not found. 'oauth_callback' is not a valid view function or pattern name.
"GET /xero/login/ HTTP/1.1" 500 109247
Internal Server Error: /xero/login/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 113, in get
    response = xero.authorize(callback_uri=redirect_url)
AttributeError: 'DjangoOAuth2App' object has no attribute 'authorize'
"GET /xero/login/ HTTP/1.1" 500 99157
Internal Server Error: /xero/login/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\xero\views.py", line 113, in get
    return oauth.xero.authorize_redirect(request, redirect_uri)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\authlib\integrations\django_client\apps.py", line 25, in authorize_redirect
    rv = self.create_authorization_url(redirect_uri, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\authlib\integrations\base_client\sync_app.py", line 313, in create_authorization_url
    raise RuntimeError('Missing "authorize_url" value')
RuntimeError: Missing "authorize_url" value
"GET /xero/login/ HTTP/1.1" 500 108657
Not Found: /
"GET / HTTP/1.1" 404 2392
Not Found: /favicon.ico
Not Found: /favicon.ico
Forbidden: /fixed-assets/asset-settings/
"POST /fixed-assets/asset-settings/ HTTP/1.1" 403 45
Forbidden: /fixed-assets/asset-settings/
"POST /fixed-assets/asset-settings/ HTTP/1.1" 403 58
Forbidden: /fixed-assets/asset-settings/
"POST /fixed-assets/asset-settings/ HTTP/1.1" 403 58
Forbidden: /fixed-assets/asset-settings/
"POST /fixed-assets/asset-settings/ HTTP/1.1" 403 58
Forbidden: /fixed-assets/asset-settings/
"POST /fixed-assets/asset-settings/ HTTP/1.1" 403 58
Internal Server Error: /fixed-assets/asset-settings/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
"POST /fixed-assets/asset-settings/ HTTP/1.1" 500 86354
Forbidden: /fixed-assets/asset-settings/
"POST /fixed-assets/asset-settings/ HTTP/1.1" 403 58
Unauthorized: /fixed-assets/asset-settings/
"POST /fixed-assets/asset-settings/ HTTP/1.1" 401 183
Internal Server Error: /fixed-assets/asset-settings/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
"POST /fixed-assets/asset-settings/ HTTP/1.1" 500 86456
Internal Server Error: /fixed-assets/asset-settings/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
"POST /fixed-assets/asset-settings/ HTTP/1.1" 500 86456
Internal Server Error: /fixed-assets/asset-settings/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
"POST /fixed-assets/asset-settings/ HTTP/1.1" 500 86456
Internal Server Error: /fixed-assets/asset-settings/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\fixed_assets\views.py", line 12, in post
    request_data = {
TypeError: 'int' object is not a mapping
"POST /fixed-assets/asset-settings/ HTTP/1.1" 500 99010
Internal Server Error: /fixed-assets/asset-settings/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\fixed_assets\views.py", line 11, in post
    request_data = {
TypeError: 'int' object is not a mapping
"POST /fixed-assets/asset-settings/ HTTP/1.1" 500 98983
Internal Server Error: /fixed-assets/asset-settings/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
"POST /fixed-assets/asset-settings/ HTTP/1.1" 500 86456
Internal Server Error: /fixed-assets/asset-settings/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
"POST /fixed-assets/asset-settings/ HTTP/1.1" 500 86456
Unauthorized: /fixed-assets/asset-settings/
"POST /fixed-assets/asset-settings/ HTTP/1.1" 401 183
Bad Request: /fixed-assets/asset-settings/
"POST /fixed-assets/asset-settings/ HTTP/1.1" 400 122
Bad Request: /fixed-assets/asset-settings/
"POST /fixed-assets/asset-settings/ HTTP/1.1" 400 36
Bad Request: /fixed-assets/asset-settings/
"POST /fixed-assets/asset-settings/ HTTP/1.1" 400 57
Unauthorized: /fixed-assets/asset-settings/
"GET /fixed-assets/asset-settings/ HTTP/1.1" 401 183
Unauthorized: /fixed-assets/asset-settings/
"GET /fixed-assets/asset-settings/ HTTP/1.1" 401 183
Internal Server Error: /auth/login/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\decorators\debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\dj_rest_auth\views.py", line 48, in dispatch
    return super().dispatch(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\dj_rest_auth\views.py", line 127, in post
    self.login()
  File "C:\Users\scorp\PycharmProjects\xero_assets\auth\views.py", line 6, in login
    super(LoginView, self).login()
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\dj_rest_auth\views.py", line 70, in login
    self.access_token, self.refresh_token = jwt_encode(self.user)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\dj_rest_auth\utils.py", line 14, in jwt_encode
    refresh = JWTTokenClaimsSerializer.get_token(user)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework_simplejwt\serializers.py", line 66, in get_token
    return cls.token_class.for_user(user)  # type: ignore
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework_simplejwt\tokens.py", line 207, in for_user
    token = cls()
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework_simplejwt\tokens.py", line 67, in __init__
    self.set_exp(from_time=self.current_time, lifetime=self.lifetime)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework_simplejwt\tokens.py", line 162, in set_exp
    self.payload[claim] = datetime_to_epoch(from_time + lifetime)
TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'int'
"POST /auth/login/ HTTP/1.1" 500 137895
Not Found: /favicon.ico
Not Found: /
"GET / HTTP/1.1" 404 2505
Bad Request: /fixed-assets/asset-settings/
"PATCH /fixed-assets/asset-settings/ HTTP/1.1" 400 36
Bad Request: /fixed-assets/asset-types/
"POST /fixed-assets/asset-types/ HTTP/1.1" 400 51
Bad Request: /fixed-assets/asset-types/
"POST /fixed-assets/asset-types/ HTTP/1.1" 400 51
Bad Request: /fixed-assets/asset-types/
"POST /fixed-assets/asset-types/ HTTP/1.1" 400 51
Bad Request: /fixed-assets/asset-types/
"POST /fixed-assets/asset-types/ HTTP/1.1" 400 50
Bad Request: /fixed-assets/asset-types/
"POST /fixed-assets/asset-types/ HTTP/1.1" 400 51
Bad Request: /fixed-assets/asset-types/
"POST /fixed-assets/asset-types/ HTTP/1.1" 400 51
Bad Request: /fixed-assets/asset-types/
"POST /fixed-assets/asset-types/ HTTP/1.1" 400 51
Bad Request: /fixed-assets/asset-types/
"POST /fixed-assets/asset-types/ HTTP/1.1" 400 51
Bad Request: /fixed-assets/asset-types/
"POST /fixed-assets/asset-types/ HTTP/1.1" 400 51
Bad Request: /fixed-assets/asset-types/
"POST /fixed-assets/asset-types/ HTTP/1.1" 400 51
Bad Request: /fixed-assets/asset-types/
"POST /fixed-assets/asset-types/ HTTP/1.1" 400 51
Bad Request: /fixed-assets/asset-types/
"POST /fixed-assets/asset-types/ HTTP/1.1" 400 51
Bad Request: /fixed-assets/asset-types/
"POST /fixed-assets/asset-types/ HTTP/1.1" 400 51
Not Found: /fixed-assets/asset-types/3/
"GET /fixed-assets/asset-types/3/ HTTP/1.1" 404 51
Bad Request: /fixed-assets/asset-types/
"PATCH /fixed-assets/asset-types/ HTTP/1.1" 400 40
Not Found: /favicon.ico
Not Found: /favicon.ico
Bad Request: /fixed-assets/assets/
"POST /fixed-assets/assets/ HTTP/1.1" 400 382
Internal Server Error: /fixed-assets/assets/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\fixed_assets\views.py", line 206, in patch
    assets.save()
AttributeError: 'QuerySet' object has no attribute 'save'
"PATCH /fixed-assets/assets/ HTTP/1.1" 500 99796
Internal Server Error: /admin/fixed_assets/asset/2/change/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\contrib\admin\options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\contrib\admin\options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\contrib\admin\options.py", line 1855, in _changeform_view
    "subtitle": str(obj) if obj else None,
  File "C:\Users\scorp\PycharmProjects\xero_assets\fixed_assets\models.py", line 144, in __str__
    return '{} - {} - {}'.format(self.name, self.rate, self.effective_life)
AttributeError: 'Asset' object has no attribute 'name'
"GET /admin/fixed_assets/asset/2/change/ HTTP/1.1" 500 119431
Internal Server Error: /admin/fixed_assets/asset/2/change/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\contrib\admin\options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\contrib\admin\options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\contrib\admin\options.py", line 1855, in _changeform_view
    "subtitle": str(obj) if obj else None,
  File "C:\Users\scorp\PycharmProjects\xero_assets\fixed_assets\models.py", line 144, in __str__
    return '{} - {} - {}'.format(self.name, self.rate, self.effective_life)
AttributeError: 'Asset' object has no attribute 'name'
"GET /admin/fixed_assets/asset/2/change/ HTTP/1.1" 500 119431
Bad Request: /fixed-assets/assets/
"POST /fixed-assets/assets/ HTTP/1.1" 400 65
Not Found: /favicon.ico
Method Not Allowed: /fixed-assets/assets/
"GET /fixed-assets/assets/ HTTP/1.1" 405 40
Not Found: /favicon.ico
Internal Server Error: /fixed-assets/assets-list/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\fixed_assets\views.py", line 241, in list
    filter_queryset: QuerySet = self.filter_queryset(queryset)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
AttributeError: 'OrderingFilter' object has no attribute 'filter_queryset'
"GET /fixed-assets/assets-list/?ordering=asset_name HTTP/1.1" 500 108118
Internal Server Error: /fixed-assets/assets-list/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\fixed_assets\views.py", line 241, in list
    filter_queryset: QuerySet = self.filter_queryset(queryset)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
AttributeError: 'OrderingFilter' object has no attribute 'filter_queryset'
"GET /fixed-assets/assets-list/?ordering=asset_name HTTP/1.1" 500 108130
Internal Server Error: /fixed-assets/assets-list/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\fixed_assets\views.py", line 241, in list
    filter_queryset: QuerySet = self.filter_queryset(queryset)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
AttributeError: 'OrderingFilter' object has no attribute 'filter_queryset'
"GET /fixed-assets/assets-list/ HTTP/1.1" 500 107572
Not Found: /favicon.ico
Internal Server Error: /fixed-assets/asset-numbers/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\fixed_assets\views.py", line 253, in get
    assets: Union[QuerySet, Asset] = Asset.objects.get(user=user)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\db\models\query.py", line 640, in get
    raise self.model.MultipleObjectsReturned(
fixed_assets.models.Asset.MultipleObjectsReturned: get() returned more than one Asset -- it returned 2!
"GET /fixed-assets/asset-numbers/ HTTP/1.1" 500 107792
Internal Server Error: /fixed-assets/asset-types/
Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\fields.py", line 446, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\fields.py", line 96, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'Asset' object has no attribute 'asset_account'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\scorp\PycharmProjects\xero_assets\fixed_assets\views.py", line 132, in get
    return self.get_paginated_response(serializer.data)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\relations.py", line 190, in get_attribute
    return super().get_attribute(instance)
  File "C:\Users\scorp\PycharmProjects\xero_assets\venv\lib\site-packages\rest_framework\fields.py", line 479, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `asset_account` on serializer `AssetTypeSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Asset` instance.
Original exception text was: 'Asset' object has no attribute 'asset_account'.
"GET /fixed-assets/asset-types/ HTTP/1.1" 500 149394
